server:
  port: 8090

spring:
  application:
    name: graphql-gateway

  graphql:
    graphiql:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:

      productService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      reviewService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  timelimiter:
    instances:

      reviewService:
        timeoutDuration: 3s

      productService:
        timeoutDuration: 3s