server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-platform
    username: postgres
    password: Admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:

      paymentService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      productService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  timelimiter:
    instances:

      paymentService:
        timeoutDuration: 3s

      productService:
        timeoutDuration: 3s